# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy dotnet core app to Azure Function App - weathertoemailapp(UAT)
# SHA256:xvcY0Je7/gjPeD5J4sPHQOuMqwWy9+ZdC4z9OG7jXPw
on:
  push:
    branches:
      - UAT
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '3.1.301'  # set this to the dotnet version to use

jobs:
  automerge:
    runs-on: windows-latest
    steps:
      - uses: reitermarkus/automerge@v2
        with:
          token: ${{ secrets.MERGE_TOKEN }}
          merge-method: merge
          do-not-merge-labels: never-merge
          dry-run: true
          
  build-and-deploy:
    runs-on: windows-latest
    steps:        
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2
  
    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: pwsh
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet build --configuration Release --output ./output
        popd

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: 'weathertoemailapp'
        slot-name: 'PRODUCTION'
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_084720d9cdbd4e9f944a2ee7915f691e }}             
  
